### ISSUE TITLE
Material vs Bootstrap

### ISSUE THREAD

**Issue by edodso2** [ethral/foodhunter#1]
Do you think material _and_ bootstrap are needed? I would be interested in working on removing the dependency on bootstrap without breaking your layout and styling. It looks like it is only used for the navbar, food map item and some basic row/col we could just use flexbox for. We could also just import the grid system from bootstrap if we find we need it for complex layouts later.

**Comment by ethral** [comment]
Haha ..
 I actually started out with bootstrap and was going to work with flex but
kept it off for later ...
Sure man ... are you in the office tomorrow? ... if you have like 15 mins
tomorrow to explain .. just want to understand at a high level how we can
go about with the pull request and all..

Thanks Eric
Appreciate it

**Comment by edodso2** [comment]
With the removal of bootstrap I think it will be helpful to have global styles for some of the helpful classes we are losing like .container. I have created a new folder for global styles so we can organize them. The new .container class can live in the layout.css file:

![image](https://user-images.githubusercontent.com/12009947/51717373-9ef50700-200e-11e9-9e19-ff3d780ccfad.png)

**Comment by ethral** [comment]
makes sense man ... 👍
