### ISSUE TITLE
Fix TSLint errors

### ISSUE THREAD

**Issue by edodso2** [ethral/foodhunter#11]
Lots of TSLint errors in the project. I would recommend installing the plugin in VSCode if thats what you are using so you can see when there is an error while coding:

![image](https://user-images.githubusercontent.com/12009947/51717065-59840a00-200d-11e9-94bf-2d2e8f4c5a9a.png)

**Comment by ethral** [comment]
thanks eric , i did disable TSLint.

Got it enables again. will make the corrections over the weekend once i finish the edit functionality.

**Comment by edodso2** [comment]
I have also used prettier in the past: https://prettier.io/ 

Basically we can setup a hook so that when we commit the code it will format it. 9 times out of 10 prettier will get the code formatted so that there are no tslint errors. I can set it up if you are on board since I already have the config handy on another project.

**Comment by ethral** [comment]
so basically , it would catch the tslint errors we miss and fix it on check in once the hooking up is done via the package.json?
that would be cool man

**Comment by edodso2** [comment]
Yea, It's pretty handy. If we were to run it on the repo now it would probably fix all the linter errors.

**Comment by ethral** [comment]
i was fixing stuff manually to figure out what exactly the linter wants me to do.
got the gist of it.

process : 
basically take the lastest code from git , hook up prettier and check back everything and let prettier run its magic ?

**Comment by edodso2** [comment]
So I hooked the pre commit hook up with prettier. I also had to add pre-commit package for obvious reasons. However, it was pretty slow formatting _all_ the files before commit so I used lint-staged and husky to only format the files that are staged to make it very fast.

Some more info here: https://prettier.io/docs/en/precommit.html
