### ISSUE TITLE
not able to commit code , styles error comes up

### ISSUE THREAD

**Issue by ethral** [ethral/foodhunter#12]
![image](https://user-images.githubusercontent.com/17237907/51785255-07cda380-2123-11e9-9615-f4c8f06e969a.png)

when  i try to commit , i get this error
and karma starts up

**Comment by edodso2** [comment]
Did you take latest code and run npm install first before committing?

**Comment by ethral** [comment]
I did a git pull and then npm install .. put the firebase config file .. I
had made some changes to 4-files or so ...
They had some merge conflicts , so I physically corrected them .. and tried
to commit them  and that's when this issue started to happen ... but the
code runs fine in my local

**Comment by edodso2** [comment]
By default the pre-commit hook will run ng test but when configured with
husky and lint staged it should not do that. You can try to remove the
husky and lint-staged sections of package.json it should commit the code
fine.

**Comment by ethral** [comment]
just discarded all my changes and took and cloned again .. :)
